### ISSUE TITLE
teredo ipv6 test (2001:0000:4136:e378:8000:63bf:3fff:fdd2) 测试结果不太对

### ISSUE THREAD

**Issue by ShenHongFei** [daidr/zxinc-ipv6#2]
`2001:0000:4136:e378:8000:63bf:3fff:fdd2` 这个 IP 对应的 data.ipv4 应该是 `192.0.2.45`，不是 `190.201.28.135`
https://github.com/daidr/zxinc-ipv6/blob/main/test/main.js#L73

这个 IP 在 wiki 里面也有解释
https://zh.wikipedia.org/wiki/Teredo%E9%9A%A7%E9%81%93#IPv6%E5%9C%B0%E5%9D%80

我这里解析后应该是
IANA 特殊地址／Teredo 隧道地址 → teredo 服务器 65.54.227.120 美国／Microsoft 公司; 客户端 192.0.2.45 IANA／保留地址'

**Comment by daidr** [comment]
确实有问题，我尝试修了一下，你看看现在还有问题么 #3

**Comment by ShenHongFei** [comment]
看起来没问题了
